Feature/phone input component redesign
Lend-AI/design-system pull request #5
Opened 2023-09-18 09:44 UTC by nofar-shlomo

2023-09-18 11:27 UTC, gennady-gramovich requested changes
Good job, one change is needed

2023-09-18 11:27 UTC, gennady-gramovich commented on projects/lendai-us/design-system/src/lib/phone-input/phone-input.component.ts
> +    const number = parseNumber(this.code + phone ?? '');
const number = parseNumber(this.code && phone ? this.code + phone : '');

2023-09-19 07:09 UTC, gennady-gramovich approved these changes, later dismissed

2023-09-26 11:50 UTC, mordechai-dror requested changes

2023-09-26 11:50 UTC, mordechai-dror commented on projects/lendai-us/design-system/src/assets/fonts/icomoon.svg
it seems that while adding new "search" icon the one from previous is deleted ("done" one). is it intentional? besides it paths for several other icons have also been changed

2023-09-26 11:50 UTC, mordechai-dror commented on projects/lendai-us/design-system/src/lib/phone-input/phone-input.component.html
> +  <button type="button" mat-button class="countries-button" matPrefix [disabled]="isDisabled || isReadonly"
please align attributes one per line... this way it will be easier to read them

2023-09-26 11:50 UTC, mordechai-dror commented on projects/lendai-us/design-system/src/lib/phone-input/phone-input.component.html
> +  <input #input matInput [(ngModel)]="phone" [disabled]="isDisabled" [readonly]="isReadonly" [required]="isRequired"
please align attributes one per line... this way it will be easier to read them

2023-09-26 11:50 UTC, mordechai-dror commented on projects/lendai-us/design-system/src/lib/phone-input/phone-input.component.scss
> +::ng-deep {
`::ng-deep` should be scoped by `:host`

2023-09-26 11:50 UTC, mordechai-dror commented on projects/lendai-us/design-system/src/lib/phone-input/phone-input.component.ts
> +    FilterPipe,
i don't see usage of filter pipe and reactive forms module, if they indeed aren't used, we can remove their imports

2023-09-26 11:50 UTC, mordechai-dror commented on projects/lendai-us/design-system/src/lib/phone-input/phone-input.component.ts
> +        item.name.toString().toLowerCase().indexOf(searchText.toLowerCase()) !==
split the `item.name` modification and condition expression into separate lines to increase readability, `searchString` can be lower cased only once outside of the loop, return statement can be simplified e.g. 

```typescript
searchText = searchText.toLowerCase();
this.filteredList = this.countries.filter(item => {
  const name = item.name.toString().toLowerCase();
  return name.indexOf(searchText) !== -1;
});
...
```

2023-09-26 11:50 UTC, mordechai-dror commented on projects/lendai-us/design-system/src/lib/phone-input/phone-input.component.ts
> +    this.countries.filter(item => {
why `.filter` method is used here if its result isn't used?

2023-10-02 06:44 UTC, mordechai-dror requested changes

2023-10-02 06:44 UTC, mordechai-dror commented on projects/lendai-us/design-system/src/lib/phone-input/phone-input.component.ts
> +          // tap(this.updateFlag.bind(this)),
you can clean up unnecessary comments

2023-10-02 06:44 UTC, mordechai-dror commented on projects/lendai-us/design-system/src/lib/phone-input/phone-input.component.ts
> +      // this.value = callingCode.substring(1);
you can clean up unnecessary comments

2023-10-03 08:46 UTC, mordechai-dror approved these changes

2023-10-03 08:47 UTC, merged